declare function makeRequest(method: any, url: any, timeout?: number): Promise<unknown>;
declare function isValidPluscode(code: any): boolean;
declare function isValidWhatFreeWords(str: any): boolean;
declare function LatLngToWhatFreeWords(latitude: any, longitude: any): Promise<unknown>;
declare function What3WordsToLatLng(words: any): Promise<unknown>;
declare function LatLngToPluscode(latitude: any, longitude: any): Promise<unknown>;
declare function PlusCodeToLatLng(code: any): Promise<unknown>;
declare function getLatLngInfo(baseurl: any, latitude: any, longitude?: boolean): Promise<unknown>;
declare function helloWorld(): string;
declare function PopulationDensity(latitude: any, longitude?: boolean): Promise<unknown>;
declare function PopulationDensityBuffer(buffer_in_meters: any, latitude: any, longitude?: boolean): Promise<unknown>;
declare function PopulationDensityWalk(minutes: any, latitude: any, longitude?: boolean): Promise<unknown>;
declare function PopulationDensityBike(minutes: any, latitude: any, longitude?: boolean): Promise<unknown>;
declare function PopulationDensityCar(minutes: any, latitude: any, longitude?: boolean): Promise<unknown>;
declare function AdminLevel1(latitude: any, longitude?: boolean): Promise<unknown>;
declare function AdminLevel2(latitude: any, longitude?: boolean): Promise<unknown>;
declare function AdminLevel2FuzzyLev(name: any): Promise<unknown>;
declare function AdminLevel2FuzzyTri(name: any): Promise<unknown>;
declare function UrbanStatus(latitude: any, longitude?: boolean): Promise<unknown>;
declare function UrbanStatusSimple(latitude: any, longitude?: boolean): Promise<unknown>;
declare function NearestPlace(latitude: any, longitude?: boolean): Promise<unknown>;
declare function NearestPoi(latitude: any, longitude?: boolean): Promise<unknown>;
declare function NearestBank(latitude: any, longitude?: boolean): Promise<unknown>;
declare function NearestBankDist(latitude: any, longitude?: boolean): Promise<unknown>;
