declare let dialog: any;
declare function insertCell(val: any): Promise<void>;
declare function oneDown(adr: any): string;
declare function processMessage(arg: any): Promise<void>;
declare function getSelectedCells(): Promise<string>;
declare function toggleProtection(event: any): void;
declare function openDialogPopup(event: any): Promise<void>;
declare function openDialogNIRAS(event: any): void;
declare function openDialogOPM(event: any): void;
declare function openDialogSATF(event: any): void;
declare function openDialogHELP(event: any): void;
