declare function htmlTable(obj: any): string;
declare let localEvent: number;
declare const southWest: L.LatLng;
declare const northEast: L.LatLng;
declare const bounds: L.LatLngBounds;
declare const osm: L.TileLayer;
declare const esri: L.TileLayer;
declare const s2_dry: L.TileLayer;
declare const s2_wet: L.TileLayer;
declare const white: L.TileLayer;
declare const map: L.Map;
declare const all_classes: L.TileLayer;
declare const urban_non_urban: L.TileLayer;
declare const bank_distance: L.TileLayer;
declare const road_density: L.TileLayer;
declare const viirs: L.TileLayer;
declare const surf_dry: L.TileLayer;
declare const surf_wet: L.TileLayer;
declare const tex_b04: L.TileLayer;
declare const tex_b08: L.TileLayer;
declare const tex_b12: L.TileLayer;
declare const basemaps: {
    OpenStreetMap: L.TileLayer;
    'Esri WorldMap': L.TileLayer;
    'Dry Season 2019 (RGB)': L.TileLayer;
    'Wet Season 2019 (RGB)': L.TileLayer;
    'Without background': L.TileLayer;
};
declare const overlaymaps: {
    'Classification (All)': L.TileLayer;
    'Classification (Urb/Rur)': L.TileLayer;
    'Nighttime Lights 2019': L.TileLayer;
    'Distance to Banks': L.TileLayer;
    'Road Density': L.TileLayer;
    'Dry season SAR (Coh2 * Db)': L.TileLayer;
    'Wet season SAR (Coh2 * Db)': L.TileLayer;
    'PCA Texture Red': L.TileLayer;
    'PCA Texture NIR': L.TileLayer;
    'PCA Texture SWIR': L.TileLayer;
};
declare function addMarkers(themap: any, markername: any): void;
